### ISSUE TITLE
missing build folder

### ISSUE THREAD

**Issue by mburger343** [grant/go-diagram#4]
Hi,

     I am looking at running the go-diagram to generate uml for a small go program I am working on. I tried running the example (in windows) by entering in the command prompt "go-diagram .\example1". The webpage (http://localhost:port) just contains a link to demo.go. When I click on the link, it opens demo.go in the web browser. Looking at go-diagram\server.go, there is a call in main() to http.Dir("./app/build"). Navigating through the go-diagram source code, there does not appear to be a build folder under app, so I'm guessing this is the problem. Is build something that is supposed to be auto-generated when building go-diagram, or is this something missing from the source code.

Thanks!

**Comment by omac777** [comment]
Hi there,

I'm trying to get go-diagram to work here on a Debian Sid box.  
I got a setup error related to nodejs/babel but I'm not familiar how to interpret node stuff.  A nudge in the right direction would be greatly appreciated.
The short of it is in "css/index.styl", there was an:
ERROR in Path must be a string. Received undefined

The verbose steps to install and build along with the detailed error output follow:
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install -y nodejs
logout/login
go get github.com/grant/go-diagram
cd /home/loongson/Code/go/src/github.com/grant/go-diagram/

sudo npm i -g npm-upgrade
sudo npm-upgrade babel-core
sudo npm run build


> go-diagram@0.0.2 build /home/loongson/Code/go/src/github.com/grant/go-diagram/app
> webpack --config webpack.config.js --progress --colors -p

Hash: 02804b4f411e4092c332  
Version: webpack 1.13.2
Time: 13165ms
       Asset      Size  Chunks             Chunk Names
js/bundle.js    539 kB       0  [emitted]  main
  index.html  52 bytes          [emitted]  
   [0] multi main 52 bytes {0} [built]
    + 477 hidden modules

WARNING in js/bundle.js from UglifyJs
Condition always true [./~/react/lib/ReactMount.js:764,0]
Condition left of && always true [./~/json3/lib/json3.js:5,0]
Side effects in initialization of unused variable components [./~/react-transform-catch-errors/lib/index.js:13,0]
Dropping side-effect-free statement [./~/redbox-react/lib/index.js:312,0]
Dropping unused function _assign__ [./~/redbox-react/lib/index.js:303,0]
Dropping unused function _set_original__ [./~/redbox-react/lib/index.js:311,0]
Dropping unused function _update_operation__ [./~/redbox-react/lib/index.js:317,0]
Condition always true [./~/react/lib/findDOMNode.js:46,0]
Condition always true [./~/react/lib/instantiateReactComponent.js:80,0]
Dropping unreachable code [./~/react/lib/shouldUpdateReactComponent.js:40,0]
Condition always true [./~/react/lib/traverseAllChildren.js:158,0]
Side effects in initialization of unused variable _reactRouter [./js/components/Struct.js:6,0]
Side effects in initialization of unused variable fieldType [./js/components/UMLDiagram.js:160,10]
Side effects in initialization of unused variable appActions [./js/components/UMLDiagram.js:9,12]
Side effects in initialization of unused variable _reactRedux [./js/components/UMLDiagram.js:10,0]
Side effects in initialization of unused variable CHANGE_PROJECT_NAME [./js/constants/AppConstants.js:9,13]
Side effects in initialization of unused variable CHANGE_OWNER_NAME [./js/constants/AppConstants.js:10,13]
Side effects in initialization of unused variable DELETE_STRUCT [./js/constants/AppConstants.js:11,13]
Side effects in initialization of unused variable CHANGE_STRUCT_NAME [./js/constants/AppConstants.js:12,13]
Side effects in initialization of unused variable CHANGE_STRUCT_FIELD_TYPE [./js/constants/AppConstants.js:13,13]
Side effects in initialization of unused variable CHANGE_STRUCT_FIELD_NAME [./js/constants/AppConstants.js:14,13]
Side effects in initialization of unused variable ADD_STRUCT_FIELD [./js/constants/AppConstants.js:15,13]
Side effects in initialization of unused variable REMOVE_STRUCT_FIELD [./js/constants/AppConstants.js:16,13]
Side effects in initialization of unused variable SET_PACKAGE_DATA [./js/constants/AppConstants.js:17,13]
Side effects in initialization of unused variable ADD_STRUCT [./js/constants/AppConstants.js:18,13]
Side effects in initialization of unused variable state [./~/react-router/lib/Link.js:106,0]
Condition always true [./~/react-router/lib/Redirect.js:49,0]
Condition always true [./js/app.js:46,4]
Side effects in initialization of unused variable dispatch [./js/components/SearchBox.js:25,10]
Side effects in initialization of unused variable projectName [./js/components/pages/HomePage.js:46,6]
Side effects in initialization of unused variable ownerName [./js/components/pages/HomePage.js:47,6]
Side effects in initialization of unused variable _reactRouter [./js/components/pages/HomePage.js:9,0]
Condition always true [./~/error-stack-parser/error-stack-parser.js:6,0]
Dropping unreachable code [./~/error-stack-parser/error-stack-parser.js:8,5]
Condition always true [./~/history/lib/createMemoryHistory.js:69,0]
Condition always true [./~/jquery/dist/jquery.js:9778,0]
Side effects in initialization of unused variable nextFrame [./~/react-input-autosize/lib/AutosizeInput.js:9,0]
Condition always true [./~/react-router/lib/IndexRedirect.js:49,0]
Condition always true [./~/react-router/lib/IndexRoute.js:46,0]
Condition always true [./~/react-router/lib/Route.js:50,0]
Condition always true [./~/react/lib/ReactDOMComponent.js:907,0]
Dropping side-effect-free statement [./~/react/lib/ReactEventListener.js:72,0]
Dropping unused function handleTopLevelWithPath [./~/react/lib/ReactEventListener.js:98,0]
Dropping unused variable DOCUMENT_FRAGMENT_NODE_TYPE [./~/react/lib/ReactEventListener.js:26,0]
Dropping side-effect-free statement [./~/redbox-react/lib/lib.js:134,0]
Dropping unused function _assign__ [./~/redbox-react/lib/lib.js:125,0]
Dropping unused function _set_original__ [./~/redbox-react/lib/lib.js:133,0]
Dropping unused function _update_operation__ [./~/redbox-react/lib/lib.js:139,0]
Side effects in initialization of unused variable filenameHasLoaders [./~/redbox-react/lib/lib.js:17,0]
Side effects in initialization of unused variable isFilenameAbsolute [./~/redbox-react/lib/lib.js:28,0]
Side effects in initialization of unused variable makeUrl [./~/redbox-react/lib/lib.js:38,0]
Side effects in initialization of unused variable makeLinkText [./~/redbox-react/lib/lib.js:62,0]
Condition always true [./~/stackframe/stackframe.js:6,0]
Dropping unreachable code [./~/stackframe/stackframe.js:8,5]
Condition always false [./~/style-loader/addStyles.js:24,0]
Dropping unreachable code [./~/style-loader/addStyles.js:25,0]
Condition always true [./~/style-loader!./~/css-loader!./~/stylus-loader!./css/index.styl:10,0]
Condition always true [./~/underscore/underscore.js:48,0]
Dropping unreachable code [./~/underscore/underscore.js:54,0]
Condition always true [./~/underscore/underscore.js:1543,0]
Condition always true [./~/url/~/punycode/punycode.js:511,0]
Dropping unreachable code [./~/url/~/punycode/punycode.js:518,2]
Side effects in initialization of unused variable freeExports [./~/url/~/punycode/punycode.js:5,0]
Side effects in initialization of unused variable freeModule [./~/url/~/punycode/punycode.js:7,0]
Dropping unused variable key [./~/url/~/punycode/punycode.js:56,0]
Condition always true [(webpack)-dev-server/client?http:/localhost:3000:9,0]
Side effects in initialization of unused variable scriptHost [(webpack)-dev-server/client?http:/localhost:3000:5,0]
Condition always true [(webpack)/hot/only-dev-server.js:6,0]
Dropping unreachable code [(webpack)/hot/only-dev-server.js:76,0]

ERROR in ./~/css-loader!./~/stylus-loader!./css/index.styl
Module build failed: TypeError: /home/loongson/Code/go/src/github.com/grant/go-diagram/app/css/index.styl:6:1
   2| 
   3| @import 'vendor/**/*'
   4| @import 'base/**/*'
   5| @import 'components/**/*'
   6| 
------^

Path must be a string. Received undefined

    at assertPath (path.js:7:11)
    at extname (path.js:1433:5)
    at new SourceMapper (/home/loongson/Code/go/src/github.com/grant/go-diagram/app/node_modules/stylus/lib/visitor/sourcemapper.js:41:7)
    at Renderer.render (/home/loongson/Code/go/src/github.com/grant/go-diagram/app/node_modules/stylus/lib/renderer.js:94:9)
    at /home/loongson/Code/go/src/github.com/grant/go-diagram/app/node_modules/stylus-loader/index.js:149:12
    at tryCatchReject (/home/loongson/Code/go/src/github.com/grant/go-diagram/app/node_modules/when/lib/makePromise.js:840:30)
    at runContinuation1 (/home/loongson/Code/go/src/github.com/grant/go-diagram/app/node_modules/when/lib/makePromise.js:799:4)
    at Fulfilled.when (/home/loongson/Code/go/src/github.com/grant/go-diagram/app/node_modules/when/lib/makePromise.js:590:4)
    at Pending.run (/home/loongson/Code/go/src/github.com/grant/go-diagram/app/node_modules/when/lib/makePromise.js:481:13)
    at Scheduler._drain (/home/loongson/Code/go/src/github.com/grant/go-diagram/app/node_modules/when/lib/Scheduler.js:62:19)
    at Scheduler.drain (/home/loongson/Code/go/src/github.com/grant/go-diagram/app/node_modules/when/lib/Scheduler.js:27:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
 @ ./css/index.styl 4:14-118 13:2-17:4 14:20-124

ERROR in Path must be a string. Received undefined
