### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by DjangoPeng** [grant/go-diagram#9]
I have failed to install go-diagram on Mac OSX. The error logs are as below:
```
ERROR in ./~/css-loader!./~/stylus-loader!./css/index.styl
Module build failed: TypeError: /Users/Patient/Projects/caicloud/go-diagram/app/css/index.styl:6:1
   2|
   3| @import 'vendor/**/*'
   4| @import 'base/**/*'
   5| @import 'components/**/*'
   6|
------^

Path must be a string. Received undefined

    at assertPath (path.js:28:11)
    at extname (path.js:1473:5)
    at new SourceMapper (/Users/Patient/Projects/caicloud/go-diagram/app/node_modules/stylus/lib/visitor/sourcemapper.js:41:7)
    at Renderer.render (/Users/Patient/Projects/caicloud/go-diagram/app/node_modules/stylus/lib/renderer.js:94:9)
    at /Users/Patient/Projects/caicloud/go-diagram/app/node_modules/stylus-loader/index.js:149:12
    at tryCatchReject (/Users/Patient/Projects/caicloud/go-diagram/app/node_modules/when/lib/makePromise.js:840:30)
    at runContinuation1 (/Users/Patient/Projects/caicloud/go-diagram/app/node_modules/when/lib/makePromise.js:799:4)
    at Fulfilled.when (/Users/Patient/Projects/caicloud/go-diagram/app/node_modules/when/lib/makePromise.js:590:4)
    at Pending.run (/Users/Patient/Projects/caicloud/go-diagram/app/node_modules/when/lib/makePromise.js:481:13)
    at Scheduler._drain (/Users/Patient/Projects/caicloud/go-diagram/app/node_modules/when/lib/Scheduler.js:62:19)
    at Scheduler.drain (/Users/Patient/Projects/caicloud/go-diagram/app/node_modules/when/lib/Scheduler.js:27:9)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
 @ ./css/index.styl 4:14-114 13:2-17:4 14:20-120

ERROR in Path must be a string. Received undefined
```

**Comment by sundarv85** [comment]
I get the same too

**Comment by jguenther-va** [comment]
Same for me (OSX)

**Comment by Crossfire972** [comment]
Same Here

**Comment by audgster** [comment]
Ditto

**Comment by DjangoPeng** [comment]
@grant Are you still maintain the repo?

**Comment by grant** [comment]
Sorry the code isn’t working. It looks like there a stylus loader that needs to be upgraded and broke for some reason. I would love if someone could dig in the code and find out.

@DjangoPeng I will accept pull requests! But I am not actively working on this project.
